<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\FileType;
use App\Models\Software;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Ramsey\Uuid\Uuid;

class SoftwareSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /* The Table Contents
           id (autogenerated)
           title (human-readable title)
           filename (with extension)
           file_extension (without prefix dot)
           description (nullable)
           file_size (bytes)
           version (nullable, string)
           mime_type (look up in file types table to add id)
           uuid (autogenerated)
           downloads (0 default)
           category (category tags not stored in table)
           members_only (true default)
           expires (nullable, null default, integer number of hours)
         */
        $baseItems = [
            /* unknown for testing */
            [
                'id' => null,
                'title' => 'Unknown',
                'filename' => 'unknown.unknown',
                'file_extension' => 'unknown',
                'description' => "Unknown Item - dummy to test",
                'file_size' => 0,
                'version' => "1.2.3.4.5.6.7.8.9.0",
                'categories' => ['UNKNOWN',],
                'image' => 'icon-Ubuntu.webp',
            ],
            /* Ubuntu 20.10 */
            [
                'id' => null,
                'title' => 'Ubuntu',
                'version' => "20.10",
                'filename' => "ubuntu-20.10-desktop-amd64.iso",
                'categories' => ['Linux', 'OS', 'Desktop',],
                'description' => null,
                'file_extension' => 'iso',
                'size' => 2_942_003_200,
            ],
            /* MS Windows 10 */
            [
                'id' => null,
                'title' => "MS Windows",
                'version' => "10",
                'filename' => "en-us_windows_10_consumer_editions_version_21h2_x64_dvd_6cfdb144.iso",
                'categories' => ['Windows', 'OS', 'Desktop',],
                'description' => null,
                'file_extension' => 'iso',
                'size' => 5_883_697_152,
            ],
            /* MS Office Mac */
            [
                'id' => null,
                'title' => "Office for Mac",
                'version' => "16.41.20091302",
                'categories' => ['Application', 'Office',],
                'description' => null,
                'filename' => "Microsoft_Office_16.41.20091302_BusinessPro_Installer.pkg",
                'file_extension' => 'pkg',
                'size' => 1_650_519_860,
            ],
            /* GreenShot */
            [
                'id' => null,
                'title' => "Greenshot",
                'version' => "1.2.10",
                'categories' => ['Application', 'Graphic',],
                'description' => "Screen Capture and Annotation Software",
                'filename' => "Greenshot-INSTALLER-1.2.10.6-RELEASE.exe",
                'file_extension' => "exe",
                'size' => 1_783_200,
            ],
            /* MongoDB */
            [
                'id' => null,
                'title' => "MongoDB",
                'version' => "4.4.3",
                'categories' => ['Database', 'NoSQL',],
                'description' => null,
                'filename' => "mongodb-windows-x86_64-enterprise-4.4.3.exe",
                'file_extension' => "exe",
                'size' => 455_698_349,
            ],
            /* MS Windows 11 */
            [
                'id' => null,
                'title' => "MS Windows",
                'version' => "11",
                'filename' => "en-us_windows_11_consumer_editions_updated_nov_2021_x64_dvd_4222adf1.iso",
                'categories' => ['Windows', 'Desktop', 'OS',],
                'description' => null,
                'file_extension' => 'iso',
                'size' => 5_565_052_928,
            ],
            /* MS Windows Server 2022 */
            [
                'id' => null,
                'title' => "MS Windows Server",
                'version' => "2022",
                'filename' => "en-us_windows_server_2022_x64_dvd_620d7eac.iso",
                'categories' => ['Windows', 'Server', 'OS',],
                'description' => null,
                'file_extension' => 'iso',
                'size' => 5_550_684_160,
            ],
        ];

        foreach ($baseItems as $item) {

            if (is_null($item['file_extension'])){
                $item['file_extension'] = substr($item['filename'], -(strrpos($item['filename'], '.', -1) - 1));
            }
            $mimeType = FileType::where('file_extension', $item['file_extension'])->first();
            $item['mime_type'] = $mimeType->mime_type ?? 1;
            $item['uuid'] = Str::uuid();

            $software = Software::create(
                [
                    'id' => $item['id'],
                    'title' => $item['title'],
                    'filename' => $item['filename'],
                    'file_extension' => $item['file_extension'] ?? 'unknown',
                    'description' => $item['description'] ?? null,
                    'version' => $item['version'] ?? null,
                    'file_size' => $item['size'] ?? 0,
                    'uuid' => $item['uuid'],
                    'mime_type' => $item['mime_type'],
                    'downloads' => 0,
                    'members_only' => true,
                    'expires' => null,
                ]
            );

            $software->attachTags($item['categories']);
        }

        $countItems = count($baseItems);
        $this->command->getOutput()->writeln("<info>            Added {$countItems} software items.");

    }

}
